[package]
name = "pflegebedarf"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
version = "0.1.0"
publish = false

[dependencies]
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
lettre = "0.8"
lettre_email = "0.8"
rusqlite = "0.14"
time = "0.1"
error-chain = "0.12"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
