[package]
name = "pflegebedarf"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
version = "0.1.0"
edition = "2018"
publish = false

[features]
default = ["build-ui"]
build-ui = []

[dependencies]
futures = "0.1"
hyper = "0.12"
url = "1.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lettre = "0.8"
lettre_email = "0.8"
rusqlite = "0.15"
time = "0.1"
error-chain = "0.12"

[build-dependencies]
flate2 = "1.0"
rayon = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
