[package]
name = "pflegebedarf"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
version = "0.1.0"
edition = "2018"
publish = false

[features]
default = ["build-ui"]
build-ui = []

[dependencies]
tokio = "0.1"
hyper = "0.12"
url = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lettre = "0.9"
lettre_email = "0.9"
rusqlite = "0.20"
time = "0.1"

[build-dependencies]
flate2 = "1.0"
rayon = "1.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
