[package]
name = "pflegebedarf"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
version = "0.1.0"
publish = false

[dependencies]
iron = "0.6"
router = "0.6"
bodyparser = "0.8"
persistent = "0.4"
urlencoded = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
lettre = "0.8"
lettre_email = "0.8"
rusqlite = "0.14"
time = "0.1"
error-chain = "0.12"
regex = "1.0"
lazy_static = "1.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
