[package]
name = "api"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]

[dependencies]
time = "0.1"
url = "1.6"
rusqlite = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rust-ini = "0.10"

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
