[package]
name = "api"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]

[dependencies]
time = "0.1.38"
url = "1.6.0"
rusqlite = "0.13.0"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.9"

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
